# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
Imports: rflann
Remotes: YeeJeremy/rflann,
  bbuchsbaum/neuroim2
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov()'