# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ".time", # <plot.baseline_model>
  ".block", # <plot.baseline_model>
  "xf", # <estimate_hrf>
  "index", # <cells.fmri_model>
  "type", # <cells.fmri_model>
  ".", # <reshape_coef>
  "row_id", # <reshape_coef>
  "phi_global", # <runwise_lm>
  "sigma_global", # <runwise_lm>
  "name", # <meta_contrasts>
  NULL
))
