# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' AR(p) whitening of data and design matrices
#'
#' Applies a causal AR filter defined by `phi_coeffs` to both `Y` and `X`
#' matrices in place. The filter equation is:
#' 
#' v_t = y_t - sum(phi_k * y_{t-k}, k=1 to p)
#'
#' @param Y Numeric matrix of data (time x voxels)
#' @param X Numeric matrix of design (time x predictors)  
#' @param phi_coeffs Numeric vector of AR coefficients (length p)
#' @param exact_first_ar1 Logical, apply exact variance-normalizing scaling 
#'   of first sample for AR(1). For p > 1, no scaling is applied.
#' @param parallel Logical, enable OpenMP parallelization across columns
#'
#' @details 
#' The function assumes valid (stationary) AR coefficients are provided.
#' No checks for stationarity are performed. 
#' 
#' For exact_first_ar1 = TRUE and p = 1, the first residual is multiplied 
#' by sqrt(1 - phi^2) for proper variance normalization. This scaling is 
#' only applied for AR(1) models.
#'
#' @return List with components 'Y' and 'X' containing the whitened matrices
#' @keywords internal
ar_whiten_inplace <- function(Y, X, phi_coeffs, exact_first_ar1 = FALSE, parallel = TRUE) {
    .Call('_fmrireg_ar_whiten_inplace', PACKAGE = 'fmrireg', Y, X, phi_coeffs, exact_first_ar1, parallel)
}

#' AR(p) whitening with void return (no-copy version)
#'
#' More efficient version that modifies matrices in place without returning
#' copies. Use when you don't need the return values.
#'
#' @param Y Numeric matrix of data (time x voxels) - modified in place
#' @param X Numeric matrix of design (time x predictors) - modified in place
#' @param phi_coeffs Numeric vector of AR coefficients (length p)
#' @param exact_first_ar1 Logical, apply exact scaling of first sample for AR(1)
#' @param parallel Logical, enable OpenMP parallelization across columns
#'
#' @keywords internal
ar_whiten_void <- function(Y, X, phi_coeffs, exact_first_ar1 = FALSE, parallel = TRUE) {
    invisible(.Call('_fmrireg_ar_whiten_void', PACKAGE = 'fmrireg', Y, X, phi_coeffs, exact_first_ar1, parallel))
}

instantaneous_correlation_rcpp <- function(x, y, eta = NA_real_, tau_half = NA_real_, offset = 0L, warmup = -1L, fill = "zero") {
    .Call('_fmrireg_instantaneous_correlation_rcpp', PACKAGE = 'fmrireg', x, y, eta, tau_half, offset, warmup, fill)
}

