# Update codemeta.json when DESCRIPTION changes
on:
  push:
    paths:
      - 'DESCRIPTION'
    branches: [main, master]
  workflow_dispatch:

name: Update codemeta.json

jobs:
  update-codemeta:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::codemetar

      - name: Update codemeta.json
        run: |
          if (!require("codemetar", quietly = TRUE)) {
            install.packages("codemetar")
          }
          codemetar::write_codemeta()
        shell: Rscript {0}

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add codemeta.json
          git diff --staged --quiet || git commit -m "Update codemeta.json via GitHub Actions"
          git push 